### ISSUE TITLE
SU 10 Beta - Changes ?

### ISSUE THREAD

**Issue by EisernUnion** [Fragtality/PilotsDeck#11]
Hi,
do you know what has changed by the SU 10 Beta ... Only the  "views" still work ?!

**Comment by Fragtality** [comment]
You are referring to the Fenix or FBW Profile?
Then probably FSUIPC is not working with SU10 (the Views dont need FSUIPC):
https://forum.simflight.com/topic/95631-fsuipc-write-lvars-not-working-in-msfs-su10-beta/
When John Dowson does not support Betas, there is nothing I can do - PilotsDeck is "just" a Client for FSUIPC.

**Comment by EisernUnion** [comment]
The Fenix.... hmm, it looks like an fsuipc issue... Supporting Beta's is one thing; to get the stuff working being prepared when beta turns in to stable the other thing ;)

**Comment by Fragtality** [comment]
Closing Issue - sadly nothing I can fix on my Side.

**Comment by Fragtality** [comment]
@EisernUnion 
I got an Idea: maybe the "legacy way" to read & write Lvars might work in SU10 Beta?
Please try Version [0.7.2](https://github.com/Fragtality/PilotsDeck/blob/master/PilotsDeck-latest.zip) and set "Fsuipc7LegacyLvars" to "true" in the PilotsDeck.dll.config File!

**Comment by EisernUnion** [comment]
Im not sure ... it works when set to true....
but e.g. FenixA320 e.g. some Light's like Beacon, Wing are working; Nav Lights (only short press)... RwyTurn, Landing, Strobes dont work when button is pressed but showing the correct state when set inside the cockpit

**Comment by Fragtality** [comment]
That's strange, another User reported that the Workaround is working. Did you restart the StreamDeck-Software after you made the change to the .config File?

What is also strange: your Issue does not seem to relate to Lvars, but to running Lua Scripts instead (and I would not be aware that there are Issue with that and SU10beta). That's the Difference between the working and non-working Lights you have reported.
Did you change something else in your FSUIPC Installation? Maybe the Scripts are not started by FSUIPC, that would be one explanation why that is not working.

**Comment by Fragtality** [comment]
Closing Issue due to missing Feedback
