### ISSUE TITLE
no respond from stream deck to 320

### ISSUE THREAD

**Issue by zuoqinyuan** [Fragtality/PilotsDeck#13]
[StreamDeck0.log](https://github.com/Fragtality/PilotsDeck/files/9639861/StreamDeck0.log)
[PilotsDeck20220925.log](https://github.com/Fragtality/PilotsDeck/files/9639862/PilotsDeck20220925.log)

hi，there is the log,now the stream deck can read the plane state,for example AP or FD,but from stream deck to msfs don't work

**Comment by zuoqinyuan** [comment]
with 0.7.3
![Desktop Screenshot 2022 09 25 - 04 11 14 11](https://user-images.githubusercontent.com/114316311/192125282-f451d8c5-f4dd-4514-af2e-0a6db81ef9e9.png)

**Comment by zuoqinyuan** [comment]
![image](https://user-images.githubusercontent.com/114316311/192125450-5f9e28e1-e8fb-4ee2-858a-504ee08d22f1.png)

**Comment by Fragtality** [comment]
Wrong FSUIPC Version installed, you need Beta 7.3.9h like described in the Readme and Changelogs.
https://forum.simflight.com/topic/96718-fsuipc7-739-beta-now-available-for-su10/

**Comment by zuoqinyuan** [comment]
got beta now,seems like no output to fsuipc...

**Comment by Fragtality** [comment]
Then I need more Details:
- From which PilotsDeck Version did you upgrade?
- So the Buttons correctly change (read is possible) but no "write"? Do Actions with Type Script and Lvar both don't work?
- If Lvar based Actions don't work: Does it work if you set "Fsuipc7LegacyLvars" to true in the Plugin Config? (Restart of StreamDeck Software required)
- I need a more clean/specific (PilotsDeck) Log - the one you gave me was over hours and I had no specific Information when what happened.
Stop the StreamDeck Software, delete the PilotsDeck Logs, start the StreamDeck Software. Then start the Sim and start a Flight with the Fenix. Try some Actions without changing much folders. Close the Sim.

**Comment by zuoqinyuan** [comment]
I have change the unicode to EN-US,now its completely gone...no any read,i start feeling there is a unicode proble from msfs...i will redownload it and try again

**Comment by Fragtality** [comment]
What does "change the unicode" mean?! You mean like "Change date, time, or number formats" in Windows? Should not be an Issue since the Plugin does not rely on the System Setting for Number Conversions.

What about the Informations I requested?

**Comment by zuoqinyuan** [comment]
[StreamDeck0.log](https://github.com/Fragtality/PilotsDeck/files/9642471/StreamDeck0.log)
[PilotsDeck20220926.log](https://github.com/Fragtality/PilotsDeck/files/9642475/PilotsDeck20220926.log)
sorry internet way too slow

**Comment by zuoqinyuan** [comment]
[FSUIPC7.zip](https://github.com/Fragtality/PilotsDeck/files/9642501/FSUIPC7.zip)
here is the fsuipc ini

**Comment by zuoqinyuan** [comment]
and is there any way to let me know,where is the problem,any test for FSUIPC?i havent see any report when i push the Stream D button

**Comment by Fragtality** [comment]
From the Logs:
`[ERROR]: **** The installed WASM version is 0.9.0 while the WAPI is expecting WASM version 0.5.9. Please update the WASM module as this may cause issues. `

While I see in the ini that FSUIPC7 7.3.9h was installed, it seems the WASM Module of FSUIPC was not updated. Please try to reinstall FSUIPC and make sure WASM is installed/updated.

With WASM not correctly installed, Lvar-based and Script-based Actions (like Nose and Landing Light) will not work - both read und write Lvars.

Did you tried to set the Fsuipc7LegacyLvars Parameter to true? Would have been interesting to know if at least the Lvar-based Actions work again. (that would have been something you could have tested ...)

It is also normal in that Situation that you don't see a yellow warning Sign (I guess that is meant with "report"?) on the StreamDeck: FSUIPC is Connected, the Plugin can send it's commands to FSUIPC.

**Comment by zuoqinyuan** [comment]
now
  [INFO]: **** Starting FSUIPC7 WASM Interface (WAPI) version 0.5.10 (WASM version 0.5.9)

fsuipc7 legacylvar now set to true,and i'm think pilotdesk get input.
when i hold button too long time,log have
[ERR] ActionBase: OnButtonUp NOT successful (Long: True) for Action "MCDU" [HandlerSwitch] Write: 1:5 | LongWrite: False - 
and stream deck log also have log

i think there problem between PDesk and webstock server?the webstock connected sim and can detect LVars.

how does the pilotdesk connect with webstock?

**Comment by zuoqinyuan** [comment]
does it have any IP address or port requirement?i'm using port 2048 and the Number of Sockets Connected is always 0
i have test with [http://fsuipcwebsockets.paulhenty.com/#jsresponses](url) it will change to 1

**Comment by Fragtality** [comment]
I say it AGAIN: Make sure the WASM Module is also updated. SOLVE THAT.
Everything is else is just wasting both of our time!

John just released the official/GA 7.3.9 Build on fsuipc.com - therefore the corresponding WASM Module (0.9.0) is also available as dedicated Download. Get that and install the "fsuipc-lvar-module" in your Community Folder.

**Comment by Fragtality** [comment]
Now we are getting somewhere ;)
Please provide me PilotsDeck Log File of that Session! And the Log "FSUIPC_WASMIF" (and _prev) found in the Plugins Main Directory.

**Comment by Fragtality** [comment]
Hmm, if I remember correctly you need to add this to the FSUIPC7.ini:
```
[WAPI]
EnableWAPI=Yes
LogLevel=Info
```

Then the FSUIPC_WASMIF.log and FSUIPC_WASMIF_prev.log should be generated (located where the PilotsDeck Executable is).

The Issue can't be resolved here since FSUIPC/WASM are not working correctly - John has to look into this! Please go ahead and post the Issue (WASM not running/connecting) in the FSUIPC Support Forums: https://forum.simflight.com/forum/183-fsuipc7-msfs/
It is vital that you provide Logs for John: add the above to your ini and start the sim, load a flight and exit. Attach the FSUIPC7.log and .ini from FSUIPC and both FSUIPC_WASMIF Logs (from the Plugin Folder) there. I'll try to assist there.

**Comment by zuoqinyuan** [comment]
got solution,unintall and delete FSUIPC7 and PD plugin folder,reinstall all of them
problem is the old PilotsDeck still run with the old WASM
`**** Starting FSUIPC7 WASM Interface (WAPI) version 0.5.10 (WASM version 0.5.9)`
it can't detect the new WASM 0.9.0

**Comment by Fragtality** [comment]
You said it is Version 0.7.3? That has the correct (and still latest) DLL to connect to WASM 0.9.0 ...

I made some research - the C# Client for FSUIPC seems to need an Update as well. Paul pushed a new Version and I recompiled the Plugin. Please download and try: https://github.com/Fragtality/PilotsDeck/blob/master/PilotsDeck-latest.zip

**Comment by zuoqinyuan** [comment]
yes,i mean if we not delete old 0.7.3 folder,it will still try to connect with 0.5.9
i was try last time at that time,reading the log try to find something,then i see it want connect with 0.5.9
but finelly it work now ;)

**Comment by zuoqinyuan** [comment]
there some buttom dont work,like land and nose light dome LT,Wx also not work.all number read from plane was gone.
_+button also not working

**Comment by zuoqinyuan** [comment]
i wanna learn some lua programming for flight sim,do you have any recommend document?

**Comment by Fragtality** [comment]
> there some buttom dont work,like land and nose light dome LT,Wx also not work.all number read from plane was gone.
> _+button also not working
That could relate to some LUA-Errors I saw in your Logs on the FNX320-* Files. But I can't understand them, since the reported error/line number does not match to the version which is uploaded. And the uploaded Scripts are working correctly.
So I don't know what you did there again - redownload the Scripts again.

> i wanna learn some lua programming for flight sim,do you have any recommend document?
Look in the FSUIPC7 Folder under Documents ...

**Comment by zuoqinyuan** [comment]
now its work,thanks
