### ISSUE TITLE
Potential enhancements for use with x-Plane 

### ISSUE THREAD

**Issue by Samhaho** [Fragtality/PilotsDeck#14]
Hi Fragtality, 

I got to know you work thanks to the excellent PilotsDeck_FNX. Few days ago, I discovered PilotsDeck. This is an amazing piece of software. It is flexible, powerful, reliable and easy to use platform to configure/program Stream Deck for flight simulation. Many thanks for sharing.

At this point, to make it simple in terms of learning and admin/maintenance I am trying to use the features that do not need external files such as Macro and Lua scripts . So far for MSFS I have been able to do what I need, thanks  in particular to the "calculator" Action type.

I am now using your platform to configure Stream Deck for XP12. It is working great. However there are a couple of "simple" enhancement/extensions that I would like to suggest to make the software even more flexible and powerful when used with  x-Plane (sorry if those features exist already and couldn't figure out how to use them):

1) Toggle action
For Dynamic button, having a second action (very similar to the "long press" but with a normal press) would be very handy to implement a toggle action that requires the use of x-Plane commands such as "command_pos_0" and "command_pos_1" (or up and down commands). The first and second actions will be activated alternatively.

2) Multiple commands
It would be very useful if it were possible to send several x-plane commands as a single Action. This will save buttons for actions that often need to happen simultaneously such as controlling landing lights left and right with the same button

Again, thanks for this great plugin (I bought my Stream Deck only to be used with it) and keep the excellent work.

Samer

**Comment by Fragtality** [comment]
Hello Samhaho ,

thanks for your Feedback! 😃 
<br/> 

> At this point, to make it simple in terms of learning and admin/maintenance I am trying to use the features that do not need external files such as Macro and Lua scripts . So far for MSFS I have been able to do what I need, thanks in particular to the "calculator" Action type.

Comes down to Preferences I guess! I'm using CalculatorCodes in the Fenix Profile to replace some Lua-Oneliner-Functions, but everything more than a simple push or turn I prefer Lua-Scripts for easier Maintenance 😅 
<br/>
<br/>

> Toggle action
For Dynamic button, having a second action (very similar to the "long press" but with a normal press) would be very handy to implement a toggle action that requires the use of x-Plane commands such as "command_pos_0" and "command_pos_1" (or up and down commands). The first and second actions will be activated alternatively.

Assuming I understood it correctly: That is exactly the Situation where Lua comes into play! There you could do such a mechanic (and much more). 😉 
I'll look into this if there is at least a quick way to do that - like using the Control Status Value and its On/Off Value for that. But no promises that I'll add that Feature! (It is basically you and every other User is already able to do that with Lua).
<br/>
<br/>

> Multiple commands
It would be very useful if it were possible to send several x-plane commands as a single Action. This will save buttons for actions that often need to happen simultaneously such as controlling landing lights left and right with the same button

Mostly: Nope! Reason: Lua 😉
Also: Simple Buttons can be added to StreamDeck's Multi-Actions. Sure it would not display the State, but you can Chain multiple Commands with that also.
BUT: Thinking about it, the FS Control Codes (aka SimEvents) also support chaining of multiple Commands in one Action. If there was no technical Reason why XP Commands don't support that, I'll add that!

**Comment by Samhaho** [comment]
Thank you for the quick response.

 

While waiting to see if my suggestions make sese to implement, I’ll go ahead and try to play with Lua (I’ll have to learn first). But if I understand well, in the context of your plugin Lua scripts are to be executed by FSPUIPC. How do you do that with x-plane? What am I missing? In summary what are the things to do to execute a simple Lua script that sends a simple command to x-plane? Can you just point out an example please?

 

 

Samer

**Comment by Fragtality** [comment]
Well, if you can handle CalculatorCode with it's it RPN (I'm honestly don't really understand it), then Lua should not be a Challenge for you 😅 

For X-Plane there is FlyWithLua! It is even more powerful, since you create Custom Commands and DataRefs with it that can be used in the Plugin Actions (like normal XP Commands and DataRefs).
Just have a look at my ToLiss Profile/Integration 😉

**Comment by Samhaho** [comment]
You answered the question I had in mind. The code is FlybyLua, the entry point to the code is a CUSTOM command. Therefore, from the PilotsDeck POV it will be processed like any other command. Clear now.

 

I will look to the Toliss integration example (I had missed that, sorry).

 

Many thanks.

 

Samer

**Comment by Fragtality** [comment]
Multiple XP-Commands in one Action will come 😉 

They will work similar to the FS Control Codes, they're chained with a colon (XPCMD1:XPCMD2 ...)

**Comment by Samhaho** [comment]
Great! Thanks

 

Let’s see if the double actions (toggle) could be done..

 

Samer

**Comment by Fragtality** [comment]
Try the latest Version and tell me what you think :wink:
https://github.com/Fragtality/PilotsDeck/raw/master/PilotsDeck-latest.zip
<br/>
Note that you now need the .NET **7** Runtimes! (Link in the Requirements)

**Comment by Samhaho** [comment]
Thanks for introducing the enhancements but sorry but I couldn’t see the difference (new features).

 

I had just removed the previous version of the plugin and put the new one in your link below. Is this how I am supposed to run the new version?

 

I tried the commands chain separated by “:” but the plugin did not accept it(! Mark)

 

Also, I do not see the “Controls and XP-Commands can now toggle” as commented on the Github in front of the PilotsDeck file that was updated few hours ago.

 

What am I doing wrong?

 

By the way, when you replace a previous version of Stream deck plugin with a new one, what happens to the existing button configuration?

 

Samer

**Comment by Fragtality** [comment]
I don't know why you didn't see the comment on the File - it is/was there!
BUT: It is my fault, I did not update my Release-Scripts to use the Net7 Binary 😅 😅 
Use the link again, now it is the new Version (RLY!) 😃
<br/>
You can generally just upgrade to every new Version - if something would break existing Profiles or if something more than just "drop it in" has to be done for the Upgrade, it is mentioned in the Release-Notes of that Version. Like the Command-Syntax-Change with Version 0.6.2 or the Change to .NET with Version 0.7.0 for Example. And no, in that Version (0.7.7) there are no such Changes :wink:
The Button/Action Configuration is stored by StreamDeck itself, so there is nothing User-specific in the Plugin Directory. (If you don't have modified your Installation by changing the Plugin Configuration or the Plugin Manifest for example, that is assumed to be handled by the User :wink: )

**Comment by Samhaho** [comment]
Works great. Many thanks for implanting the features so quickly.

I very much appreciate your software and your support.

Keep the great job.

 

Samer

**Comment by Samhaho** [comment]
Hi Fragtality,

 

This is just to let you know that I’ve observed issues with “toggle switch with two different commands” feature. I am trying to use it with X-Plane 12 commands

 

Basically, it is misbehaving. Sometimes (I am not sure when and why) only one command out of the two alternatives is executed, either the principle or the alternate.

 

I’ll let you know if I can better identify the problem, but this happen enough often so the feature is not reliable. T

 

This is nice to have (not must have) feature, so if you think it is not worth the effort to make it work, then this is fine. Just let me know.

 

Samer

 

 

From: ***@***.*** ***@***.***> 
Sent: mardi 3 janvier 2023 15:38
To: 'Fragtality/PilotsDeck' ***@***.***>; 'Fragtality/PilotsDeck' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [Fragtality/PilotsDeck] Potential enhancements for use with x-Plane (Issue #14)

 

 

Works great. Many thanks for implanting the features so quickly.

I very much appreciate your software and your support.

Keep the great job.

 

Samer

**Comment by Samhaho** [comment]
I spent a couple of hours testing. I think I made some progress.  It looks like the behavior I have observed is not random and may not be a bug (you probably can tell).

 

The main finding for me is that the way the toggle works depends on the values set in the control states field, Is that intended?. I initially thought that the control state is only to control the display on the button and has nothing to do with the execution of the toggle commands. 

 

The context of my test is three positions light switch: steady (-1) , off(0), strobe(1) and I have the following commands: set strobe, set steady, set off, go up, go dn.

 

If I configure the button with two commands - among set strobe, set steady,  and set off- and I set the control state to match the states that reached when the commands are executed then the toggle works as intended; I tried, steady/off, strobe/off, steady/strobe; All those configurations work as long as the states in the control state fields are set to be “consistent” with the commands.

 

Now if I use the the go dn, go up, commands, things become more complicated. Since depending on the initial state of the switch we cannot necessarily know what are the “correct” values to set in the control state. With the same commands set in the command fields I can get different behavior (in terms of how the toggle works) according to the initial state of the switch and the value set (2 among 3 possible values) in the control state fields.

An example is a button configured with the two commands; set steady and go up. If I set the control states to 0 and -1 (in the two states field respectively) then the switch moves only, if the initial state is off, and the move is only one time up (the strobe position) and then gets stuck (the button tries only to trigger the command go up, the set steady command is not triggered any more). Now if (with same commands) I set the values in the control state to -1 and 0 (instead of 0 and -1) then I get different behavior: if the state in the strobe position, then it gets stuck (only the go up command is being triggered). If the initial state is off, then the switch alternates between off and steady which is the expected behavior.

 

Conclusion: using the toggle command to control two states, is OK.. Using the toggle in more than 2 state situations works “only” of the commands are to set a specific state (not up and down) and the control state values are set in a consistent way.

 

I hope all that is clear enough to be useful.

 

Samer

 

 

 

From: ***@***.*** ***@***.***> 
Sent: mercredi 4 janvier 2023 10:54
To: 'Fragtality/PilotsDeck' ***@***.***>; 'Fragtality/PilotsDeck' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [Fragtality/PilotsDeck] Potential enhancements for use with x-Plane (Issue #14)

 

Hi Fragtality,

 

This is just to let you know that I’ve observed issues with “toggle switch with two different commands” feature. I am trying to use it with X-Plane 12 commands

 

Basically, it is misbehaving. Sometimes (I am not sure when and why) only one command out of the two alternatives is executed, either the principle or the alternate.

 

I’ll let you know if I can better identify the problem, but this happen enough often so the feature is not reliable. T

 

This is nice to have (not must have) feature, so if you think it is not worth the effort to make it work, then this is fine. Just let me know.

 

Samer

 

 

From: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Sent: mardi 3 janvier 2023 15:38
To: 'Fragtality/PilotsDeck' ***@***.*** ***@***.***> >; 'Fragtality/PilotsDeck' ***@***.*** ***@***.***> >
Cc: 'Author' ***@***.*** ***@***.***> >
Subject: RE: [Fragtality/PilotsDeck] Potential enhancements for use with x-Plane (Issue #14)

 

 

Works great. Many thanks for implanting the features so quickly.

I very much appreciate your software and your support.

Keep the great job.

 

Samer

**Comment by Fragtality** [comment]
> The main finding for me is that the way the toggle works depends on the values set in the control states field, Is that intended?. I initially thought that the control state is only to control the display on the button and has nothing to do with the execution of the toggle commands.

That is intended. Why would you need to define them a second time?


> Conclusion: using the toggle command to control two states, is OK.. Using the toggle in more than 2 state situations works “only” of the commands are to set a specific state (not up and down) and the control state values are set in a consistent way.

Well then you did not formulate your Feature Request clear enough.
But also remember: you can chain XP-Commands now (you know, the other Feature you requested). So you send two times up or down. And also: you can use comparisons when defining the States, which are also used to select either Command.

**Comment by Samhaho** [comment]
I agree, I may not have formulated my request clearly, or even more,  maybe it was not that clear to me neither. Never mind, at this point, I am just trying to understand how this feature (the toggle commands) works. Despite hours of tests, it is still confusing to me . Would you mind explain it in just few sentences? More specifically how does the control states value impact the execution of the toggle commands?

 

As to the command chain, it is working great, and it is indeed very useful.

 

Manny thanks for the help

 

Samer

**Comment by Fragtality** [comment]
Check the Readme.

**Comment by Samhaho** [comment]
I looked carefully but I couldn’t see where the Readme is updated to reflect and describe the new “Toggle switch with two different commands“  feature.

 

Samer

**Comment by Samhaho** [comment]
I think I got it now (here below to share):

 

the On value (and all other values except the off) will trigger the Main command

the Off value will trigger the Alternate command

 

Please confirm or correct.

 

Samer

 

 

 

From: ***@***.*** ***@***.***> 
Sent: jeudi 5 janvier 2023 20:40
To: 'Fragtality/PilotsDeck' ***@***.***>; 'Fragtality/PilotsDeck' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [Fragtality/PilotsDeck] Potential enhancements for use with x-Plane (Issue #14)

 

I looked carefully but I couldn’t see where the Readme is updated to reflect and describe the new “Toggle switch with two different commands“  feature.

 

Samer

**Comment by Fragtality** [comment]
It is documented under "Toggle Switch" (exactly as called in the GUI). A short Ctrl+F would have found that:

> Toggle Switch: Only available on the "Display Value with Switch" Action and when either Control or XPCmd is selected as Action Type. When checked, you can specify an Alternate Action Address for a second Command (Control/XPCmd) to send. It is send when the current Control Status Value is in it the Off State (either by exact Value or Comparison). Put in another Way: with that Setting you can two different Commands depending on the current Control's State/Value, e.g. either Pull/Push a Knob or move a Switch up/down.

**Comment by Samhaho** [comment]
Apologize. For some reason I had access to the N-1 version of the Readme file.

 

All clear now. By the way, the way you implemented the toggle “feature” is even better that what I had in mind initially (which was an alternate action regardless of the control status value).

 

Thanks again for those latest enhancements, I am using them extensively and I hope other users will find them useful.

 

Samer

**Comment by Fragtality** [comment]
Great to hear 😃 

I assume the Issue can be closed then?

**Comment by Samhaho** [comment]
The request for enhancements is well fulfilled and can be closed.

 

Many thanks

 

Samer
