### ISSUE TITLE
Bug: Display Value with Switch

### ISSUE THREAD

**Issue by Flightport** [Fragtality/PilotsDeck#17]
Hi Fragtality,
thanks for the nice PilotsDeck-Application.
I use it with X-Plane 11 and it works fine so far, but I am still at the beginning with my Toliss Airbus switches.

I think I found a small bug concerning the Display Value with Switch Function.
The configuration is:
Toggle Switch with two different Commands
Special Value Indication is on
So I set Draw Rectangle to 1;1;72;72
I do not want to use any values displayed because I have a picture that says all.
So I set Hide Value: On

The result is, that the OFF-Value is not displayed, but the ON-Value is still displayed.

With Hide Value: OFF both values are displayed correctly.

Is there any parameter I can set to switch off all values or is it really a bug?
Regards
Joerg

**Comment by Flightport** [comment]
Found a way to solve the problem with using Dynamic Button which has no value displayed. 
So it is not important to invest time, but I think it is however a (small) bug ;-)

**Comment by Fragtality** [comment]
> thanks for the nice PilotsDeck-Application.

You're welcome 😃 
<br/>

> but I am still at the beginning with my Toliss Airbus switches.

You are aware that there is a premade Profile?
<br/>

> I think I found a small bug concerning the Display Value with Switch Function

Not really a Bug when you try to accomplish something never intended - like the Action Name suggests, it is about displaying a Value 😅 

Other Possibilities:
- Using a Comparison for the Indication Value. The Indication State has always precedence when it matches (and still the Hide Option will be respected).
- Using a Text-Mapping and map the numeric Values to nothing. (Just saw, forgot to mention that in the Readme. But it works, even when the UI says the Format is wrong. I'll update the Readme!)
<br/>

> Is there any parameter I can set to switch off all values or is it really a bug?

Well, the Challenge really was/is: you needed the just added "Toggle Switch" Feature but on an Action Type you've not needed. The "Simple Button" Action displays nothing (besides the Background Image which could also be set to empty), but that does not support the new "Toggle Switch".
I'll look into that, if would take much work to add the "Toggle Switch" also to the Simple Button.

**Comment by Flightport** [comment]
> I'll look into that, if would take much work to add the "Toggle Switch" also to the Simple Button.
Please do not invest too much time in that, I can live with it at the moment.
The problem I had when using the Dynamic Button was, that I had to use 2 XPlane Commands for toggling, because there is no toggle-command. This works fine with with Display value with Switch but not with the Dynamic Button, probably because there were no standard values (On = 1; Off = 0.1). But its ok for now.

Currently I have another problem but do not know, what causes the problem. After starting the application, the connection to X-Plane is sometimes not stable and sometimes even StreamDeck itself crashes or hangs.
If I have an idea, what it is, I let you know.

**Comment by Fragtality** [comment]
I've looked into that - would be little bit too messy to add it to the "Simple Button". It has no Control State normally when the Action Type is not readable.

BUT: It would be easier to just add a Checkbox to the Dynamic Button to disable the Image Swapping. So you would still need to define the On and Off State under Control States, but with that Checkbox the Button would always display the Default Image.
Would that be something that is more suitable for your Usecase?
