### ISSUE TITLE
X-Plane Commands "command once" vs "command begin/end"

### ISSUE THREAD

**Issue by Flightport** [Fragtality/PilotsDeck#19]
I add more functions to the Toliss panel and wanted to implement Pitch Trim button. The function sim/flight_controls/pitch_trim_down probably needs not only a Command Once but the complete cycle Command Begin and Command End.
So when I add the XPcommand to the config it doesn´t move.
Do you plan to add a parameter for XPlane Commands to choose the method (once or complete cycle)?

**Comment by Fragtality** [comment]
> Do you plan to add a parameter for XPlane Commands to choose the method (once or complete cycle)?

Nope. Probably never. Simple Reason: the Websocket "API" Austin has created just does not offer that. It can only send "Command Once".
For things like the Pitch Trim (or TO Conf, CVR Test, Fire Test) which you would like to click & hold, the vJoyDrv Action is more suited. You can bind the vJoy-Button inside X-Plane accordingly.
