### ISSUE TITLE
Code length limitation for the "calculator" action type

### ISSUE THREAD

**Issue by Samhaho** [Fragtality/PilotsDeck#20]
Hi Fragtality,

I am having problem with limitation in terms of RPN code  length under the "calculator" action type. I run to this several time already  but so far I could find a workaround. I know that the code runs correctly because I test it first under Mobiflight. Here is an example. This is to control the Dome light in the FBW:

(A:LIGHT POTENTIOMETER:7, number) 100 * 0 ==  
if{
1 (>K:CABIN_LIGHTS_SET) 100 (>K:LIGHT_POTENTIOMETER_7_SET) }
els{ (A:LIGHT POTENTIOMETER:7, number) 100 * 100 ==  
   if{ 1 (>K:CABIN_LIGHTS_SET) 50 (>K:LIGHT_POTENTIOMETER_7_SET) }
   els{ (A:LIGHT POTENTIOMETER:7, number) 100 * 50 ==  if{ 0 (>K:CABIN_LIGHTS_SET) 0 (>K:LIGHT_POTENTIOMETER_7_SET) }
  }}

Is this known limitation?

Keep the great work.
Sam

**Comment by Fragtality** [comment]
I hate RPN Code and would rather solve that via a Custom/Additional Offset (myOffsets.txt) and a Lua-Script, but hey ^^

I'll look into this. The Limitation as defined by the WASM-Header is 1024, so it can't be the Length (at the End what WASM would allow).

And would be **very helpful**: Are you still on 0.7.7 or are you testing already the latest build?

**Comment by Samhaho** [comment]
The reason I am using the RPN code is that I can reuse what I have done with Mobiflight. As to  Custom/Additional Offset I am not familiar with that. I'll take a look.

I am using release 7.7

One more thing. Configuring the lights in FBW require the use of Avar. Unfortunately Avar cannot be used in the control status. is this by design or just "normal" limitation?

**Comment by Fragtality** [comment]
Not an Plugin-Issue. For some Reasons the FSUIPC C# Client seems to be limited to 256 chars. I need to talk with Paul about that, nothing I can do on my side for now.

**Comment by Fragtality** [comment]
The C# Client will be updated to support the Maximum allowed by the WASM-Module. As soon as the Client is updated, I'll push it to the latest Build.

**Comment by Samhaho** [comment]
Many thanks.  I'll keep an eye on it.

**Comment by Fragtality** [comment]
@Samhaho 
Limitation is removed thanks to Paul 😃 
Try the latest Version: https://github.com/Fragtality/PilotsDeck/raw/master/Install-PilotsDeck-latest.exe

**Comment by Samhaho** [comment]
Tested the latest release. No more code length limit. Great.
Also the new installer is very handy (I like when its tells me where/what to download any required software)
Many thanks.
