### ISSUE TITLE
toggle switch in the latest 7.7

### ISSUE THREAD

**Issue by Samhaho** [Fragtality/PilotsDeck#21]
Hi,

I noticed that my toggle switches do not work any more with release 7.7 since in this version you introduced  new parameter "Monitor address" to toggle the switch (execute the alternate action) that is now different from the "Control status" which is now only used as parameter for display (this is how I understand it). I think this is very good idea.

So I had to fill the new fields with the "Monitor address" parameter along  On and Off values.  To replicate what I had before I just used in the "Monitor address" the same dataref  than what I used to have (and I still)  in the "control status" with the appropriate On/off values.

Unfortunately non of my toggle switches work anymore. Any idea?

**Comment by Fragtality** [comment]
You are not using Version 0.7.7. The separate Monitor Address was added in the current Devbuild.

Does restarting the StreamDeck Software help anything - while X-Plane is loaded and the Session is active?

**Comment by Samhaho** [comment]
You are right I am using the build you pointed to me to test the fix for the code length limitation. I’ll do what you suggested and get back to you.

**Comment by Fragtality** [comment]
Try if works now with the just updated build: https://github.com/Fragtality/PilotsDeck/raw/master/Install-PilotsDeck-latest.exe

**Comment by Samhaho** [comment]
After having set the fields as per the new model, I restarted StreamDeck while X-plane is loaded and the session is active and every thing works fine now.

The toggle switch thing is now is getting better (in terms of specification:behavior).

Many thanks

Sam

**Comment by Samhaho** [comment]
Our messages crossed. Unless you suggest otherwise I will stay with the release I have now and wait for the next release before updating.

**Comment by Fragtality** [comment]
1) You are using the Devbuild already, it makes no sense to stay with a build which does not exist anymore
2) You are the one reporting an Issue. Then you should test the Fixes I offer.

**Comment by Samhaho** [comment]
I misunderstood  it was a fix. Since my build started working after restarting Streamdeck.

No problem. Wilco

**Comment by Samhaho** [comment]
Toggles are Working great. Thanks

**Comment by Fragtality** [comment]
Especially when just created or updated 😉

**Comment by Fragtality** [comment]
@Samhaho 
There is a new Test-Build with Improvements to the Toggle Switch and a new Hold Switch Feature 😉 
https://github.com/Fragtality/PilotsDeck/issues/15#issuecomment-1416006116

**Comment by Samhaho** [comment]
I went through the changes, very promising indeed. So my myOffsets file (to transform A var to offsets) and some of my Flywithlua scripts (to implement the “hold” mode) may not be needed any more.

 

The problem is that Bitdefender is preventing me from downloading the installer, it did not do that for the previous versions, just in case of you guess why..

**Comment by Fragtality** [comment]
> I went through the changes, very promising indeed. So my myOffsets file (to transform A var to offsets) and some of my Flywithlua scripts (to implement the “hold” mode) may not be needed any more.

On the MSFS Side: Yes, the myOffsets should be History in nearly all Use-Cases. (I've deleted mine with Pleasure. The Hold Switch is also really great for FSLabs^^)

On the X-Plane Side: Depends.
If the Switch is DataRef based (and does not reset the State itself): yes.
If the Switch is CommandRef based and there is no separate Click/Release: no. The X-Plane API still does only support command_once (I can't send start & stop).
But the Beauty with X-Plane is: you can surely bind the Command to a Joystick-Button! Like a vJoy Button which is triggered from the Plugin for example 😉 (That's how I do these Test-Buttons on X-Plane)

**Comment by Fragtality** [comment]
Changes included in Release 0.7.8
