### ISSUE TITLE
nothing in fcu on  Alt, VS,Hdg,spd.

### ISSUE THREAD

**Issue by jmp44** [Fragtality/PilotsDeck#23]
Nothing in FCU page  on :  Alt, VS, Hdg, Spd all the others buttons are ok, not these.USe with for MSFS and  Fenix A320

Ido something wrong or ? . When I close MSFS the 4 button  show a "0" (nothing if MSFS). 

Can you help me. 
TY

**Comment by Fragtality** [comment]
Certainly not an Issue with the Plugin, please Contact me on flightsim.to
