### ISSUE TITLE
Installer .NET detector error

### ISSUE THREAD

**Issue by Bastocheanoncon** [Fragtality/PilotsDeck#24]
Hi,

The installer keeps telling me I don't have the correct .NET runtimes installed, even I after I follow the specific links in the installer and have installed them.

**Comment by Fragtality** [comment]
Thats strange!
Please send me the output of the following command:
dotnet --info

**Comment by Bastocheanoncon** [comment]
Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Bastocheanoncon** [comment]
So, that says only 6.03 is installed. But...
![Snag_3e1090a](https://user-images.githubusercontent.com/127154395/223477032-4040c5dd-db43-4328-b4f4-2b42b9371339.png)
![Snag_3e22373](https://user-images.githubusercontent.com/127154395/223477368-08342a96-414f-4a92-99dc-639cb77bdac0.png)

these say 7.02 is installed?

**Comment by Bastocheanoncon** [comment]
Solved. My smooth brain forgot I needed (x86) and not (x64).
