### ISSUE TITLE
PilotsDeck problems with execution

### ISSUE THREAD

**Issue by Scarebus** [Fragtality/PilotsDeck#25]
The first:  Many, many thanks for your effort and work.
Now I thing I have some type of problem when execute PilotDeck.exe. If I execute manually in Powershell is the same.
I send you log.
Why is your name in the path?

I understand if everything is installed OK I will enjoy your configuration by default in my Fenix A320 and three StreamDeck´s.

TIA
[PilotsDeck20230307_001.log](https://github.com/Fragtality/PilotsDeck/files/10911830/PilotsDeck20230307_001.log)

**Comment by Fragtality** [comment]
It is a StreamDeck Plugin, so start your StreamDeck Software.

**Comment by Scarebus** [comment]
I've already made progress, I think almost everything already works. The rotary controls of the SD+ obey but at no time is SPD HDH LAT ALT displayed, nor does the METRIC button work, so I suspect that some type of communication is failing. What could I have done wrong? Thanks for your patience

**Comment by Fragtality** [comment]
Seems like the Fenix Binary is not running (PilotsDeck_FNX2PLD). Try to start it manually when MSFS is in the Main Menu.
Make sure you read and understand the Description on flightsim.to

Metric is working fine. Don't know why it does not work.

**Comment by Fragtality** [comment]
That also works (it is on the Touch Display). I don't really have any Idea what the Problem could be. The Buttons which do not work are just simple L-Var writes. The Buttons which work use Calculator Code. But in the End they use the same Mechanic - so either both should work or should not work.

Please provide me a fresh/clean Log from the Plugin (\log Subdirectory in the Plugin-Directory):
- Stop the StreamDeck Software, delete the existing Logs
- Start the StreamDeck Software again and start your MSFS Session as you normally would
- Test these two non-working Buttons
- Stop the StreamDeck Software and provide me the Log from the Plugin

And how do you have installed the Plugin? I really hope you have used the Installer?
And if you happen to be on SU12 Beta, you would have said so, right?

**Comment by Scarebus** [comment]
Thank you very much friend, I think now everything is working well. I only have to look at the subject of the views and go deeper into the knowledge of all this that is new to me. We can close the ticket and I appreciate once again all your effort because all this is wonderful.
