### ISSUE TITLE
Sepcial address for AN225

### ISSUE THREAD

**Issue by AsukaBlackbird** [Fragtality/PilotsDeck#26]
HI，
I’m try to create a panel for AN225.
I find dev create a special addres like this.

Mach climb:
(A:AUTOPILOT FLIGHT LEVEL CHANGE, Bool) if{ (L:XMLVAR_AirSpeedIsInMach)
AirSpeedIsInMach may set at 1

IAS climb:\
(A:AUTOPILOT FLIGHT LEVEL CHANGE, Bool) if{ (L:XMLVAR_AirSpeedIsInMach)
AirSpeedIsInMach may set at 0

How can fill this to address for control states?

**Comment by Fragtality** [comment]
I don't really understand RPN Code, but I see either an A-Var or L-Var that could be read and that it will be either 1 or 0. So it is more or less copy & paste.

You are *sure* you have read and understood the Readme?

**Comment by AsukaBlackbird** [comment]
I try to learn from Readme, but English not my mother tongue. So, some part of that is too difficult to understand, please forgive me.
What I want to describe is, it have a control states when AUTOPILOT FLIGHT LEVEL CHANGE is 1 as same time XMLVAR_AirSpeedIsInMach is 1, the Mach climb light is on.
As same for IAS climb when XMLVAR_AirSpeedIsInMach is 1 and if MLVAR_AirSpeedIsInMach is 0, the AS climb Light is on.

**Comment by AsukaBlackbird** [comment]
[https://drive.google.com/file/d/1E_9vTj66aqWSipmLyCmOidLJP0p7q2wV/view?usp=sharing](url)
[https://drive.google.com/file/d/1NXFnFphwsZHFILaleWISMINm6OIHi0Co/view?usp=sharing](url)
I hope those two photo can help you to understand.
I read the Readme very carefully, but my ability is limited. Can you help me complete the correct content that needs to be fill？

**Comment by Fragtality** [comment]
Oooh - So the state is defined by two Variables? That is a little more work:

You would need to follow the "Using Values from Lua" Example. You need to read & evaluate the Values in Lua and then write the Result to a free Offset (which then can be read by the Plugin).
If the A-Var is not available as Offset per Default, you need to add it with the "myOffsets.txt" File.

P.S: Can't access the Photo's you have linked. Consider to attach them directly in your Message (just drag & drop or paste it)

**Comment by AsukaBlackbird** [comment]
Yes, state is defined by two variables. I search all SDK Documentation, it have not single variable to define state. Until I find this page, I can understand why I can't find a single variable, DEV use multiple Variables to make the Light ON.


https://docs.flightsimulator.com/html/Content_Configuration/Models/ModelBehaviors/TemplateExplorer/Asobo/Common/Subtemplates/Autopilot_Subtemplates.html?rhhlterm=LEVEL%20CHANGE&rhsearch=LEVEL%20CHANGE

![AP-225-1](https://user-images.githubusercontent.com/49277767/223682630-d8149e96-26f2-449d-b13b-b0d9a5367c54.png)
![AP-225-2](https://user-images.githubusercontent.com/49277767/223682631-ae54959c-7a54-4e88-a2fb-5e8814a09583.png)

**Comment by Fragtality** [comment]
Well, you don't need to dive into the general SDK Documentation, I don't think that will help.
The only thing interesting there is the List of all Simulation Variables (aka A-Vars): https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Simulation_Variables.htm

Check if there is Documentation for the Plane, e.g.: https://forum.inibuilds.com/topic/18326-hardware-commands-lvars/
Use FSUIPC to list all L-Vars - maybe there is a single L-Var where this State could be read from? Based on this Post there seem to be plenty of L-Vars: https://forum.inibuilds.com/topic/18427-lvars-list-for-an225/

Sometimes it's just trial and error finding the right Variable to read from! E.g. watching different L-Var / A-Vars that might hold that Information with "Display Value" Actions.

**Comment by Fragtality** [comment]
Sometimes L-Var for Trigger-Buttons 
Maybe you better ask this in the inibuild Forum?
I can't really help with a Plane which I don't have or know.

**Comment by Fragtality** [comment]
Sometimes L-Var for Trigger-Buttons (i.e. the snap back when not pressed) must be written accordingly. So they have to be set to 1 (pressed) and back to 0 again (not pressed anymore). That's why there is a "Reset Button" Option! Maybe that helps with these Variables?

Maybe you better ask this in the inibuild Forum?
I can't really help with a Plane which I don't have or know.

**Comment by AsukaBlackbird** [comment]
Thank you for help me to understand some part how to works. You are right, the easiest way is ask in the ini build forum. I will also do more tests. Thank you very much for your patience in answering my questions. I will do my best to finish this project for AN225 and post to flightsim.to. You will on my special thanks list!!
