### ISSUE TITLE
Version check fails with Stream Deck software 6.1

### ISSUE THREAD

**Issue by Tawmu** [Fragtality/PilotsDeck#27]
It seems like the installer doesn't detect the newest Stream Deck software, v6.1.0.18521.

![image](https://user-images.githubusercontent.com/1227469/225538253-6c76b907-9224-4116-b2ae-f792e0acbd35.png)

**Comment by Fragtality** [comment]
Yeah, the installer still needs some Improvements to check the Version being equal or greater.
I made a quick fix for now:
https://github.com/Fragtality/PilotsDeck/raw/master/Install-PilotsDeck-latest.exe

**Comment by Fragtality** [comment]
Pushed a new Installer with a proper Version-Check (same link)!
But be aware, the Requirements are now upped to .NET 7.0.4 and FSUIPC 7.3.18!

**Comment by richardkennedy** [comment]
Thanks for the quick fix 👍🏻

**Comment by Fragtality** [comment]
You're welcome! 😃 

Your Name sounds familiar - you where already using the Plugin, didn't you? 🤔

**Comment by richardkennedy** [comment]
> You're welcome! 😃
> 
> Your Name sounds familiar - you where already using the Plugin, didn't you? 🤔

Yep! Absolutely love it and I still want a tip jar 😂

**Comment by Fragtality** [comment]
Oh okay, so it is a general appreciation and not because you encountered that Issue 😅

**Comment by richardkennedy** [comment]
Both actually 😊

**Comment by Fragtality** [comment]
Huh, now I'm confused again. Installing a StreamDeck Update does not require to reinstall the Plugin.

**Comment by richardkennedy** [comment]
PC Rebuild 😉

**Comment by Fragtality** [comment]
Oh ic, bad luck on timing *g*

**Comment by Fragtality** [comment]
Released with 0.7.9 😃
