### ISSUE TITLE
FBW320_SYNC and FBW320_AUTO

### ISSUE THREAD

**Issue by richardkennedy** [Fragtality/PilotsDeck#29]
As the FBW320_SYNC and FBW320_AUTO files are no longer included by default since 0.7.7, users who install PilotsDeck and then utilise third party Stream Deck profiles that use these scripts - have non-functional buttons. Would it be possible to add the integrations files back into the main release (excluding your own themes which are now exclusive to flightsim.to)? If not, could you confirm that these two files (last included in dev-v0.7.7) are distributed with the MIT license as normal? 

Many thanks in advance.

**Comment by Fragtality** [comment]
They just shared the same Repo, but the published Plugin-Package never included any Integration/Profiles and they on the other hand never included the Plugin.
The FBW / A32NX Integration and Profile on flightsim.to, which is linked in GitHub, does contain these Files (and will contain them of course).

What is the matter with downloading from flightsim.to? If only the Scripts are required the rest of the the download can just be deleted afterwards?

But yeah, the Lua-Files can be considered MIT licensed. The move to only publish them on flightsim/xplane.to was for the Images from Guenseli.

**Comment by richardkennedy** [comment]
I create SD profiles and recommend that users download PilotsDeck directly from the GitHub site. Nothing at all wrong with downloading it from flightsim.to, but I'm trying to make it as simple as possible.

Thank you as always!

**Comment by Fragtality** [comment]
Then the Recommendation was a bit sub-optimal to be honest 😅 
It should not be downloaded via the Zip-Function of GitHub at all!
Always via Releases. Or the -latest File (aka Dev-Build) if instructed.

But ic, in that Use-Case it would be indeed simpler if you could link/download the Scripts directly. I'll push them to the Folder and hopefully will remember that when updating *g*
