### ISSUE TITLE
XP12 FlightFactor 757 Lamp

### ISSUE THREAD

**Issue by CornAddict** [Fragtality/PilotsDeck#31]
Plugin won't read datarefs for lamp values between 1-10. 

1-sim/AP/lampX 
(Where X is integer 1-10) will display as error

1-sim/AP/lampXX
(Where XX is integer 11+ display fine)
![Untitled](https://user-images.githubusercontent.com/108493565/232377686-2135013a-dd4a-4a65-8e03-4020634b0628.png)
![Untitled2](https://user-images.githubusercontent.com/108493565/232377955-d97f720e-fdbb-4a15-87eb-79b38711cea1.png)

**Comment by CornAddict** [comment]
This is true of further datarefs in the FF 757. Not sure if the issue is with the ac or the plugin.

**Comment by Fragtality** [comment]
It is the Plugin! The Regular Expression for a valid name assumed at least two characters to ensure validity,
Now that is only for the first Name in the Path, following Names can be one character long.

Try the latest Version and tell me how it works for you :)
https://github.com/Fragtality/PilotsDeck/raw/master/Install-PilotsDeck-latest.exe

**Comment by CornAddict** [comment]
Works perfectly now. Thanks for the update, really appreciate this plugin.

**Comment by CornAddict** [comment]
Quick question, if I may. How to control multiple values in an array simultaneously?
Looking to control the doors with dataref AirbusFBW/PaxDoorModeArray containing int[8] but not sure how to phrase this in the Command Address. AirbusFBW/PaxDoorModeArray[0][1] etc doesn't work. Thanks in advance.

**Comment by Fragtality** [comment]
There is no "Chaining" possible for any of the Variable based Commands. Only one Variable can be written.

That would be an Use-Case where Lua comes into play. There you could define a custom Command which does the Door handling - with the benefit of extra Checks. The Command can then be triggered like any other XP Command.
Take a look at the Scripts provided with my Toliss A321 Integration on x-plane.to as a Reference/Example.

**Comment by Fragtality** [comment]
Fix included in 0.7.10!
