### ISSUE TITLE
Support for X-Plane on macOS

### ISSUE THREAD

**Issue by jejenone** [Fragtality/PilotsDeck#36]
Hi! Any chance you could support macOS in the future ?

**Comment by Fragtality** [comment]
Hi there!

I don't really see that anywhere in the Future, for multiple Reasons:
- An essential Library is only available on Windows. Evaluating if a portable Graphics-Library is viable at all would take alone a considerable amount of Time before rewriting Parts of the Plugin could even start.
- There is no cross-Plattform compile, I would need to buy a Mac (never going to happen) or would need to run an illegal Copy in a VM (also not going to happen) to compile a Binary for Mac OS.
- That all in the Context that MacOS does only (officially) support a single Sim-Platform. Much Effort for very little gain.

**Comment by malah-akh** [comment]
Any plans to bring request back to the table?
