### ISSUE TITLE
Allow install using FSUIPC 4.x

### ISSUE THREAD

**Issue by NickNeverSleeps** [Fragtality/PilotsDeck#37]
I read in your readme that you technically have support for FSX:SE thru FSUIPC 4.X but your installer seems to stall on needing FSUIPC 7.3.19 - any chance there is a way to install it without this check in place? or is that line in the readme deprecated now? Would love to use this on FSX:SE (at least until someone ports FS Passengers to a more modern version of MSFS)

**Comment by Fragtality** [comment]
The Installer checks only the MSFS Requirements and for that they are checked/enforced.
For FSX you have to make sure yourself that all Requirements are installed.
But in every Case - as long as MSFS is installed you have to fulfill the Requirements (or deinstall MSFS).

**Comment by NickNeverSleeps** [comment]
my bad! I forgot I had MSFS installed too. Appreciate you and the work you put into this!

**Comment by Fragtality** [comment]
np, you're welcome 😃 
It is planned that the Installer will get an Command Line (only) Switch to disable the MSFS Requirement Check with the next Version. It is just that it's not that urgent to me 😅
