### ISSUE TITLE
Plugin stuck in waiting state after sim went to pause (PMDG 737 "pause before TOD")

### ISSUE THREAD

**Issue by hkogge** [Fragtality/PilotsDeck#42]
Hi there,

first of all: awesome app, thank you!

I encountered an issue when the sim goes into pause by using the automatic "pause before TOD" functionality in the PMDG 737:

The plugin seems to be visually stuck in the waiting state after returning, i.e., it does not update the images/state any more. It simply does seem to ignore/not read the configured read-addresses. 

I can still use the commands though (i.e., the buttons do what they are intended to do and the aircraft is reflecting the state change accordingly), so the connection to the sim is somehow still (partially) working. 

According to the log file [(PilotsDeck20231001_trunc.zip)](https://github.com/Fragtality/PilotsDeck/files/12777123/PilotsDeck20231001_trunc.zip), the sim seems to have never `unpaused`. Sim went into "pause before TOD" at `23-10-01 13:24:15.143`.

Restarting the StreamDeck software did not change anything, neither did restarting FSUIPC.

PilotsDeck: 0.7.11
FSUIPC: 7.3.2.3
MobiFlight event module: 0.7.1
StreamDeck: 6.3.0.18948
MSFS: SU13

**Comment by hkogge** [comment]
I found the reason: PMDG pauses the sim using the `SET PAUSE ON` command. I always resumed the flight using `ESC` (which lead me to the pause menu first) and then `ESC` again (to un-pause the sim), which obviously was not necessary and caused these issues.

**Solution**: explicitly call `SET PAUSE OFF` and everything works.

**Comment by Fragtality** [comment]
Faster fixed than I can answer 😅 

Glad it works!
