### ISSUE TITLE
Question: X-Plane 12 Frequency

### ISSUE THREAD

**Issue by rstalets** [Fragtality/PilotsDeck#44]
Thanks for this awesome plugin. Question - for X-Plane 12, is there a formatting option that I can use to insert a decimal point in the correct place? The dataref stores the frequencies as an integer but they're typically displayed as a float. For the life of me I can't figure out how to do it as-is. If I knew C# I would cut a PR but I don't so here we are...

Example:
![image](https://github.com/Fragtality/PilotsDeck/assets/53876939/a581a3b5-149b-4545-bf72-dd62f6a3a2e8)

Thanks!

Ryan

**Comment by Fragtality** [comment]
Yes there is, under "Value Format" 😉 
![image](https://github.com/Fragtality/PilotsDeck/assets/78614902/a20219ec-492a-4c0a-88b1-92705d3830c2)

**Comment by rstalets** [comment]
Perfect, I’ll give that a try. Sorry, I was struggling to find the right combination of scalar and format to make it work, I promise I tried! 😁

**Comment by Fragtality** [comment]
Yeah, hehe - no problem :)
