### ISSUE TITLE
FSUIPC Exception in Log

### ISSUE THREAD

**Issue by whakamolenz** [Fragtality/PilotsDeck#45]
Hi there,

Trying to use latest version as new user. Used the installer and it indicated all pre-reqs were ok.

While in sim have FSUPIC running and other apps can use it ok.

In PilotsDeck log have recurring:

23-12-22 13:10:44.469 [DBG] [ ActionController:Run             ] Refresh Tick #1875: average Refresh-Time over the last 75 Ticks: 18.002ms. (Actions: 1) (IPCValues: 1) (Images: 5) (Updates: 0) 
23-12-22 13:10:48.779 [FTL] [ ConnectorMSFS:Process            ] Exception in Process Call! (Exception: FSUIPC.FSUIPCException) 

Attached log below.

Buttons either stay with 3 dots or go to XXX after a time. 

Thanks for any guidance!

[PilotsDeck20231222.log](https://github.com/Fragtality/PilotsDeck/files/13747146/PilotsDeck20231222.log)

**Comment by Fragtality** [comment]
Hmm, strange Thing for Sure.

- When you are in the MSFS Main Menu - try to open the FSUIPC Window. Does it open and react?
- Are you running the latest Version of FSUIPC? If not please upgrade and try again.
- Do you run anything "as Admin". Try what it does if running normally.

**Comment by whakamolenz** [comment]
Ah sorry resolved - my network connection had changed to public - set back to private and now connects.

**Comment by Fragtality** [comment]
Ah, great to hear!
Thanks for sharing, might add this to the Readme.
