### ISSUE TITLE
--ignoremsfs flag is not working

### ISSUE THREAD

**Issue by Ragzzy-R** [Fragtality/PilotsDeck#47]
Version: 0.7.12
Operating System: Windows 10

Hello i tried to run the installer without an MSFS installation using the flag `--ignoremsfs` but i still get an MSFS requirement fail error.
![Capture](https://github.com/Fragtality/PilotsDeck/assets/2220953/f9c73198-8738-43f1-812f-80fe787bf0ff)

**Comment by Fragtality** [comment]
Good Catch!
The Problem was actually different: you should not have needed that Installation Flag at all. It is only meant for very special Cases where MSFS is indeed installed but not be used with MSFS.

Check: https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe
If that works I'll update the 0.7.12 Release with it :)

**Comment by Ragzzy-R** [comment]
hi! i actually forgot about this issue i raised and installed MSFS yesterday. So uninstalled it now and tried with both official 0.7.12(just to make sure it still fails after MSFS uninstall) and the above one. I was able to successfully install the profile with the above installer.Thank you!

![Capture](https://github.com/Fragtality/PilotsDeck/assets/2220953/b0ebcea3-c194-466b-af98-f8bee0a53e1c)

**Comment by Ragzzy-R** [comment]
Also there is a note in [this section of doc](https://github.com/Fragtality/PilotsDeck#14---installation--requirements) saying

> If you want to disable the MSFS Requirements Checks (not recommended), start the Installer with --ignoremsfs as Command Line Argument. (Don't ask me what that means)

this is actually why i used it in the first place and stumbled across this issue. So we might also want to update that part of documentation for more clarity.

**Comment by Fragtality** [comment]
Thanks for testing!

Yeah right, a Note should be added that this is only necessary when MSFS is installed but the Plugin will not be used with it (that is why that Parameter even exists)

**Comment by Fragtality** [comment]
Release and Readme updated ;)
