### ISSUE TITLE
Formatting to add a decimal doesn't work ?

### ISSUE THREAD

**Issue by Chpouky** [Fragtality/PilotsDeck#49]
Hi !

I've been trying to setup a frequency display on my Stream Deck, but for some reason I can't format a frequency value.
Following your example in the documentation, putting 3.3 in the format area should work, but it's not doing what I expect.
It adds a decimal at the very end and 3 zeroes after, instead of splitting the value with 3 values before, 3 values after.

I'm not sure if I'm doing something wrong ?

**Comment by Chpouky** [comment]
Mmh, I just tried it on another value (fuel) awith the Display Gauge (Dual) and it works there for a fuel value.

But using the COM Radio template, and picking up the frequency, it doesnt work.

**Comment by Fragtality** [comment]
Can you post more Details - like e.g. Screenshots on what you have configured on said Action?

Why would you need 3.3 on a Frequency? Is that non-VHF? Because for VHF Frequencies a 3 would be sufficient (you don't need to add leading Zeros there).

Also: are you sure the Value has a Decimal Point? Because Format is not there to add a Decimal Point.
In the Sense of manipulating the Value: you could format a Value of "25" to "25.0" - but both is still the same Value (in a different Format). But if you get a Value like 25000 which should read as "25.0" you would need to manipulate the Value with *Scale* and Format (in the Example a Scale of 0.001 with a Format of 1).

**Comment by Chpouky** [comment]
Ah !

Well, I was just dumb and didn't think of simply using Scalar to have properly formatted frequencies 😅
Using "0.001" as Scalar is perfect (so I can have 123.155 showing up).

I was too focused on the Format option :p Thank you !

**Comment by Fragtality** [comment]
Well, I would not call it dumb - it is a lot to take when starting. But it hopefully should be easy & fast once you know all the "Tools" 😃 
Have fun!

**Comment by Fragtality** [comment]
Uhm ...
https://github.com/Fragtality/PilotsDeck/tree/master/Integrations/Cirrus%20SR22%20G1000%20(XP)
😅

**Comment by Chpouky** [comment]
I saw it, but I have to admit I'm not a big fan of the layout 👀

**Comment by Chpouky** [comment]
Also, if I may have a suggestion: it would be great to be able to use Ranges for Mapping !

So for example if the Wind is between 20 and 70, I could show North East. 340 to 20 would show North, etc...

**Comment by Fragtality** [comment]
![image](https://github.com/Fragtality/PilotsDeck/assets/78614902/89e7ee5b-b134-4ff8-9609-fe46d7ceadef)
Additional Note: The first true Comparison in the user defined List is chosen.

So Ranges can be represented to some Point (the defined List does not have to be in "Order") - but it is just not made for something that only consists of Ranges and is not a Cockpit-Control.

It would be more reasonable to implement that with Lua. So figuring out the Range/Direction there and then write a distinctive Result in a custom DataRef which then can be straight-forward mapped (e.g. a Value of 0 stands for "North").

**Comment by Chpouky** [comment]
I am not familiar with LUA at all unfortunately :/ Maybe I'll check later, I'll stick with the heading in the mean time.

**Comment by Fragtality** [comment]
You can use the PilotsDeck-TLS321-Sync Script from the Toliss Script (available on x-plane.to) as an Example if you like :)

**Comment by Chpouky** [comment]
Ah ! Thanks for the tip, I'll check it out ! It's really a small detail that I want to add but it's a good QoL improvement.

**Comment by Chpouky** [comment]
Here's the profile if you want to use/check ! https://x-plane.to/file/1296/stream-deck-profile-for-pilotsdeck-cirrus-sr22
I added a few icons so everything is more coherent.

**Comment by Fragtality** [comment]
Nice Work!! 👍 

But one Tip: for the SD+ it can be beneficial to organize the Actions via Pages. That allows to quickly change the Page with a swipe on the Touch-Display. E.g. to quickly jump between Auto-Pilot and Radio!

**Comment by Fragtality** [comment]
Yeah, that is understandable. Tbh, it also "freaks out" sometimes requiring to disconnect/reconnect it. (Swipe on Touch, and Touch on Swipe -.-)
