### ISSUE TITLE
dots on all buttons, GSX PRO, B737

### ISSUE THREAD

**Issue by LukasGNN** [Fragtality/PilotsDeck#50]
Hi, 

i have installed all acc to the description but still get dots on all buttons. MFS2020, pmdg b737, streamdeck XL , v6, full verion of fscuip7.

**Comment by Fragtality** [comment]
I need the Logs, see https://github.com/Fragtality/PilotsDeck#33---troubleshooting

**Comment by LukasGNN** [comment]
[StreamDeck0.log](https://github.com/Fragtality/PilotsDeck/files/14230401/StreamDeck0.log)

pilotdeck log does not exist.

**Comment by LukasGNN** [comment]
[PilotsDeck20240210_001.log](https://github.com/Fragtality/PilotsDeck/files/14230403/PilotsDeck20240210_001.log)

**Comment by LukasGNN** [comment]
[PilotsDeck20240210.log](https://github.com/Fragtality/PilotsDeck/files/14230405/PilotsDeck20240210.log)

**Comment by Fragtality** [comment]
Alright, does not want to connect to FSUIPC and/or deems the Sim as not ready
- Using the latest FSUIPC Version? (7.4.5)
- Tried an Exclusion for the Plugin in your AV/Security Software?
- Could also be a Permission Error due to something (but not all) is "Run as admin" (not needed for the Plugin and not recommended)
- Active Pause is on?

**Comment by LukasGNN** [comment]
[PilotsDeck20240210_001.log](https://github.com/Fragtality/PilotsDeck/files/14230526/PilotsDeck20240210_001.log)

**Comment by LukasGNN** [comment]
1. latest version
2. no AV software installed
3. StreamDeck goes as normal (no run as adm).
4. Active pause is off :(

**Comment by Fragtality** [comment]
> StreamDeck goes as normal (no run as adm).

I did not mean exclusively the StreamDeck Software. I referred to all Components involved: StreamDeck Software, PilotsDeck Plugin, MSFS, FSUIPC

**Comment by LukasGNN** [comment]
> > StreamDeck goes as normal (no run as adm).
> 
> I did not mean exclusively the StreamDeck Software. I referred to all Components involved: StreamDeck Software, PilotsDeck Plugin, MSFS, FSUIPC

you are the mann! it looks like it was fsuips7 going as admin. it works now!  :) question: does the gsx window must pop up and stay on? how to hide it?

**Comment by Fragtality** [comment]
Great to hear!
FSUIPC7 does also not need to be run as Admin - unless it is installed in a Location where it should not be (e.g. Program Files).

Yeah, forget to mention that in the Readme: you can of course disable the GSX In-Game Menu (Icon on Toolbar not white, just click). Your Menu is the StreamDeck now 😉

**Comment by LukasGNN** [comment]
> Great to hear! FSUIPC7 does also not need to be run as Admin - unless it is installed in a Location where it should not be (e.g. Program Files).
> 
> Yeah, forget to mention that in the Readme: you can of course disable the GSX In-Game Menu (Icon on Toolbar not white, just click). Your Menu is the StreamDeck now 😉

sweet! :) THX. Nice job! :)

**Comment by Fragtality** [comment]
Thanks! Don't forget to Vote then 😅
