### ISSUE TITLE
Missing StreamDeckLib 2401.9.1749.0

### ISSUE THREAD

**Issue by lukefr2016** [Fragtality/PilotsDeck#52]
Hello,
I'm trying to compile your code, but vs tells me that StreamDeckLib could not be found with this version even on nuget.
On nuget I only have access to StreamDeckLib v0.5.2040 (latest).

Maybe I'm missing something...

Best regards.

**Comment by Fragtality** [comment]
Yep, that is the thing you're Missing 
https://github.com/Fragtality/StreamDeckToolkit
😉

**Comment by lukefr2016** [comment]
Thank you for the info.
Still get another error when rebuilding : 
```
2>PilotsDeck -> D:\01_DEV\StreamDeck\PilotsDeck-master\PilotsDeck\bin\Debug\net7.0-windows\PilotsDeck.dll
2>The argument 'D:\01_DEV\StreamDeck\PilotsDeck-master\PilotsDeck\BuildPlugin.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
2>Windows PowerShell
2>Copyright (C) Microsoft Corporation. All rights reserved.
2>
2>Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
2>
```

**Comment by Fragtality** [comment]
It's a Script that is only local, remove it in Project Settings (Events, Post-Build)

**Comment by lukefr2016** [comment]
Thanks and great job done and very usefull...
Thanks again.

**Comment by Fragtality** [comment]
You're welcome.

But if you have any Ideas/Suggestions it might be easier to formulate them in a GitHub Issue 😅
