### ISSUE TITLE
Cannot get FSUIPC Macros to work (P3D5, FSUIPC 6.2.0)

### ISSUE THREAD

**Issue by d00nicus** [Fragtality/PilotsDeck#56]
As title, cannot get any FSUIPC mouse macros to trigger on 0.7.12

Macros themselves are all properly loaded, and in fact work if triggered via joystick button etc

The same macros will not trigger through PilotsDeck no matter which of them I try.  Workaround is to use a vjoy button and then map that in FSUIPC, but that significantly extends the time needed to configure everything, and slows testing immensely. This workaround also removes the ability to send different commands based on a value.

Setting command type to "MACRO",  and command address to "FSLA320_SX:APUMaster" for example. Now, I'm not ruling out that I may also be an idiot - if so please do point it out to me!

`24-05-25 15:49:07.529 [DBG] [ IPCManager:RunActionUp           ] Running Action 1/1 MACRO 'FSLA320_SX:CPTERRND' on Connector 'ConnectorFSXP3D' (Value: ) 
24-05-25 15:49:07.854 [DBG] [ ActionBase:OnKeyDown             ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:08.010 [DBG] [ ActionBase:OnKeyUp               ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:08.010 [DBG] [ IPCManager:RunActionUp           ] Running Action 1/1 MACRO 'FSLA320_SX:CPTERRND' on Connector 'ConnectorFSXP3D' (Value: ) 
24-05-25 15:49:08.150 [DBG] [ ActionBase:OnKeyDown             ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:08.290 [DBG] [ ActionBase:OnKeyUp               ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:08.290 [DBG] [ IPCManager:RunActionUp           ] Running Action 1/1 MACRO 'FSLA320_SX:CPTERRND' on Connector 'ConnectorFSXP3D' (Value: ) 
24-05-25 15:49:08.330 [DBG] [ ActionBase:OnKeyDown             ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:08.461 [DBG] [ ActionBase:OnKeyUp               ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:08.461 [DBG] [ IPCManager:RunActionUp           ] Running Action 1/1 MACRO 'FSLA320_SX:CPTERRND' on Connector 'ConnectorFSXP3D' (Value: ) 
24-05-25 15:49:08.632 [DBG] [ ActionBase:OnKeyDown             ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:08.756 [DBG] [ ActionBase:OnKeyUp               ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:08.756 [DBG] [ IPCManager:RunActionUp           ] Running Action 1/1 MACRO 'FSLA320_SX:CPTERRND' on Connector 'ConnectorFSXP3D' (Value: ) 
24-05-25 15:49:08.942 [DBG] [ ActionBase:OnKeyDown             ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:09.067 [DBG] [ ActionBase:OnKeyUp               ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:09.067 [DBG] [ IPCManager:RunActionUp           ] Running Action 1/1 MACRO 'FSLA320_SX:CPTERRND' on Connector 'ConnectorFSXP3D' (Value: ) 
24-05-25 15:49:09.223 [DBG] [ ActionBase:OnKeyDown             ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:09.347 [DBG] [ ActionBase:OnKeyUp               ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:09.347 [DBG] [ IPCManager:RunActionUp           ] Running Action 1/1 MACRO 'FSLA320_SX:CPTERRND' on Connector 'ConnectorFSXP3D' (Value: ) 
24-05-25 15:49:09.389 [DBG] [ ActionBase:OnKeyDown             ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:09.518 [DBG] [ ActionBase:OnKeyUp               ] (Context: a17e44efc768ef7999d368b5d16c5e2e) (ActionID: (HandlerSwitchDisplay) () (Read: ) (Action: MACRO / ) (Long: False / MACRO / )) 
24-05-25 15:49:09.518 [DBG] [ IPCManager:RunActionUp           ] Running Action 1/1 MACRO 'FSLA320_SX:CPTERRND' on Connector 'ConnectorFSXP3D' (Value: ) 
24-05-25 15:49:12.953 [DBG] [ ActionController:Run             ] Refresh Tick #66750: average Refresh-Time over the last 75 Ticks: 31.540ms. (Actions: 12) (IPCValues: 10) (Images: 27) (Updates: 9) `

**Comment by Fragtality** [comment]
Hadn't started P3D in Ages, but a Quick-Test with my QW 787 Macros run fine 🤔 
But yeah, the Type "MACRO" with the Syntax "Filename:Macroname" is indeed correct!

Please don't share Logs like that, GitHub makes it fairly easy to attach the File.
But for that Situation the Logs don't tell anything to be fair. Macros are one of the Commands where I can't get detect a successful Execution (only if the Plugin would have an Failure sending it, which isn't the Case).

Could you please attach the Macro-File? Maybe the FSUIPC Log File also.

I don't understand why someone would use Macros for the FSL in the first Place, but whatever floats your Boat 😅

**Comment by Fragtality** [comment]
No further Feedback provided =>Closed!
