### ISSUE TITLE
Additional calculator code support

### ISSUE THREAD

**Issue by richardkennedy** [Fragtality/PilotsDeck#58]
Allow calculator code to be used as a 'Variable' input and on display value buttons.

**Comment by Fragtality** [comment]
Not possible, the API for the MF Event Module does not return any Value. Externally running Calculator Code is still not possible to my knowledge.

**Comment by Fragtality** [comment]
I was dumb and completely forgot who the Module operates 🤦‍♂️ 

Looking into it! 🤞

**Comment by Fragtality** [comment]
Check the latest Installer!

For Reading the Code has to be prefixed with "C:", e.g.
`C:(L:INI_gpu_avail, Bool) (A:EXTERNAL POWER ON:1, Bool) ! and if{ 1 } els{ 0 }`

**Comment by richardkennedy** [comment]
Perfect, appears to be working as expected 🙌🏻
