### ISSUE TITLE
LUA - A: and E: Variables

### ISSUE THREAD

**Issue by jimdabim** [Fragtality/PilotsDeck#65]
Hello,
as I am now experimenting with the new built in lua functionality, I am facing issues with reading A: and E: variables. 
L: vars work as expected :-)

Actually I want to read the Transponder (A:TRANSPONDER CODE:1, number) and the Sim rate (E:SIMULATION RATE, number).

I followed your very helpful example https://github.com/Fragtality/PilotsDeck/issues/63#issuecomment-2158855536 and used following:

SimVar("(A:TRANSPONDER CODE:1, number)")

function XPNDR_CODE()
        local xcode = SimRead("(A:TRANSPONDER CODE:1, number)")
        return xcode
end

but is returns nothing.

if I enter (A:TRANSPONDER CODE:1, number) directly in the plugin, it works as expected.
![image](https://github.com/Fragtality/PilotsDeck/assets/171567367/7b1ea84a-82f9-4630-83e4-927145702dfc)

What the hell am I doing wrong? :-)

Cheers,
Sebastian

**Comment by jimdabim** [comment]
Hello,

oh my god, I had a typo by calling my function. I had "pdmg" instead of "pmdg" and I checked it several times without noticing it.

`SimVar("C:(E:SIMULATION RATE, number)")`

works like a dream. I would have never figured that out without your help!


Your lua implementation opens so much new possobilities. 

It is A-M-A-Z-I-N-G!

thank you very much!

**Comment by Fragtality** [comment]
FYI, I have finished the Rewrite of the Plugin and pushed it to the Repository:  https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe
I would appreciate some help with Testing to get some Feedback if everything is working properly, since you like experimenting 😅  Making a **Export/Backup** of your Profiles is highly recommended! The Intention is that everything just continues to work and I had not seen any Showstoppers with my Setup - but it is better to be safe than sorry 😉 

The Readme was updated with all new Stuff (like Lua Scripts). So it would also good to know if the Readme does it Job of giving useful Information 😅 
Looking over your Issue #64, you might also be interested in the new Composite Action. It does offer more Formatting Options for Variable Values and also allows to apply a whole different Formatting based on Conditions.

**Comment by jimdabim** [comment]
Hey, 
I have some issues with my PC that require a fresh install.
I will start with the "latest" version to help you testing and give you feedback if everything works fine for me.

**Comment by jimdabim** [comment]
Hey,
I am currently at my first flight with the new version and it looks good.
The first thing I noticed is that someting has changed with the font size and the titles.
![image](https://github.com/user-attachments/assets/23dbe708-6d83-418a-98cf-b16dd16bc3dc)
The left side is how it is by default now. The right side is like it was before.

I also read the new manual. A ton of very welcomed new deatures like auto profile switching and composite actions. Also the lua documentation is very helpful with all the examples.

I will keep you updated as I test more and more.

Cheers,
Sebastian

**Comment by Fragtality** [comment]
> The first thing I noticed is that someting has changed with the font size and the titles.
image
The left side is how it is by default now. The right side is like it was before.


Yeah, that was one of the Decisions where I just could chose how to "break" existing Profiles. Since it is now a Windows/WPF App (instead of a Console App) the Text-Rendering behaves differently now.
With the Result that leaving the same Font-Size as configured would lead to most Text on the Actions being misaligned because too big for the Canvas. So I have taken the Route to convert the Size with math.ceil(FontSize * 0.916_) to make the Fonts a little smaller. Even when Profiles need slight Changes with both Options, I thought it would be better if Text-based Actions at least still look "right" in most Cases than being misaligned but keeping the configured Font Size.

<br/>

> new features like auto profile switching 

Fun Fact: it had automatic Switching before, but it is now more usable 😅 

<br/>

> I will keep you updated as I test more and more.

Thanks for Testing and your Feedback! Be sure to check if you have the latest Build - just had some commits yesterday again. There where some Changes/Fixes with some being at the very "core" of the Plugin. So would be good to know if everything works out as intended 😉

**Comment by jimdabim** [comment]
So, finally, I have "updated" my profiles for the PMDG 737 and 777.

The major work was to move all the images to respective sub folder which is a nice addition. I am a big fan of clear structures.
On top of that, I was adjusting the fonts as discussed earlier.

Apart of that, everything continued to work as expected functionality wise. :-)
Also the automatic profile switching is working superb!

With the latest SD software, Elgato introduced the feature called "Action Wheel". I played a bit with it yesterday and it basically works with Pilot deck. Only the long press is not recognized. Maybe you can do some of your magic to get this working as well :-)

As always, many many thanks for your continous effort you put into this project! It is outstanding!

greetings,
Sebastian

**Comment by Fragtality** [comment]
> The major work was to move all the images to respective sub folder which is a nice addition. I am a big fan of clear structures.

Yeah, clearer structures and easier navigation between different image-collections was the plan 😃 
Well, there would have been a way to "hack" the Profiles manually to mass-replace certain Images ^^

<br/>

> With the latest SD software, Elgato introduced the feature called "Action Wheel". I played a bit with it yesterday and it basically works with Pilot deck. Only the long press is not recognized. Maybe you can do some of your magic to get this working as well :-)

Good find! Just had a quick look: the StreamDeck Software is acting a bit strange here - it does not send dialDown / dialUp when then Action is in such a Wheel when the Dial is pressed. Don't know if that is a Bug on their Side? I mean they had added these Events for SD+ and the Encoders (never understood that, but well) and now suddenly it sends keyDown / keyUp on a Dial? 🤔 
But what is strange: with which Action did you test the Wheel? The "classic" Actions don't really make a difference - the dialDown / dialUp Events are just mapped/routed to keyDown/keyUp. The new Composite Action does make a difference here and there it would be understandable that a Long-Press on DIAL_UP does not work on Wheel - but should work if you copy/paste the Commands to KEY_UP?

**Comment by DavidEGTE** [comment]
> So, finally, I have "updated" my profiles for the PMDG 737 and 777.
> 
> The major work was to move all the images to respective sub folder which is a nice addition. I am a big fan of clear structures. On top of that, I was adjusting the fonts as discussed earlier.
> 
> Apart of that, everything continued to work as expected functionality wise. :-) Also the automatic profile switching is working superb!
> 
> With the latest SD software, Elgato introduced the feature called "Action Wheel". I played a bit with it yesterday and it basically works with Pilot deck. Only the long press is not recognized. Maybe you can do some of your magic to get this working as well :-)
> 
> As always, many many thanks for your continous effort you put into this project! It is outstanding!
> 
> greetings, Sebastian

are you able to consider sharing the pmdg profiles somehow?

**Comment by jimdabim** [comment]
I put a lot of effort into those profiles and I would really like to share them so others can benefit from that effort as well.
However, 80% of the Icons are based on screenshots of the PMDG cockpit, 10% randomly picked from the web. Those, I am not allowed to share. Only some of them are hand crafted by myself.
Also the fonts used are not mine.

I will reach out to PMDG and ask them if I am allowed to share them. If they approve, I will replace the web icons with own images.
And I will share a link to the fonts used.

But this will take some time. I will be traveling next week. After that, I will have a look.
Those profiles are for the SD+ only.

**Comment by jimdabim** [comment]
> > The major work was to move all the images to respective sub folder which is a nice addition. I am a big fan of clear structures.
> 
> Yeah, clearer structures and easier navigation between different image-collections was the plan 😃 Well, there would have been a way to "hack" the Profiles manually to mass-replace certain Images ^^
> 
> 
> > With the latest SD software, Elgato introduced the feature called "Action Wheel". I played a bit with it yesterday and it basically works with Pilot deck. Only the long press is not recognized. Maybe you can do some of your magic to get this working as well :-)
> 
> Good find! Just had a quick look: the StreamDeck Software is acting a bit strange here - it does not send dialDown / dialUp when then Action is in such a Wheel when the Dial is pressed. Don't know if that is a Bug on their Side? I mean they had added these Events for SD+ and the Encoders (never understood that, but well) and now suddenly it sends keyDown / keyUp on a Dial? 🤔 But what is strange: with which Action did you test the Wheel? The "classic" Actions don't really make a difference - the dialDown / dialUp Events are just mapped/routed to keyDown/keyUp. The new Composite Action does make a difference here and there it would be understandable that a Long-Press on DIAL_UP does not work on Wheel - but should work if you copy/paste the Commands to KEY_UP?

I will do some further tests and come back to you.

**Comment by Fragtality** [comment]
> I put a lot of effort into those profiles and I would really like to share them so others can benefit from that effort as well.

That would be really great!
If you do so, please consider to distribute them as [Profile Package](https://github.com/Fragtality/PilotsDeck#36---profile-packages) so that it is easier to install :)

<br/>

> I will do some further tests and come back to you.

FYI, I also opened a Ticket with Elegato Support - maybe it is really a Bug and gets fixed. 🤞

**Comment by jimdabim** [comment]
> If you do so, please consider to distribute them as [Profile Package](https://github.com/Fragtality/PilotsDeck#36---profile-packages) so that it is easier to install :)

For sure, I will try this :-)

**Comment by Fragtality** [comment]
> With the latest SD software, Elgato introduced the feature called "Action Wheel". I played a bit with it yesterday and it basically works with Pilot deck. Only the long press is not recognized. Maybe you can do some of your magic to get this working as well :-)

@jimdabim

I've looked into this and even got a Response from Elgato. So the Intention of that Wheel is to allow Actions that are Keypad-only to be used on an Encoder - so it is absolutely correctly from their Side to send Events for keyUp/keyDown although actually the Dial is pressed. And they also report it correctly to an specific Action: When it is in an Action-Wheel, it gets reported as Keypad. And with that PilotsDeck should also treat it correctly as a Keypad and listen for the keyUp/keyDown Events.
A quick Test with the Display Value Action (which can do both) confirmed that it is reported as-intended by Elgato and that it recognizes the Long Press.

So if you are sure that this is not an User-Error (i.e. using a Composite Action and defined the LongPress on DIAL_UP which should be KEY_UP in an Action-Wheel/Keypad), I would need the specific Steps to reproduce and Logs to check that.
