### ISSUE TITLE
Additional feature suggestion: Aditional Icons

### ISSUE THREAD

**Issue by markhlam** [Fragtality/PilotsDeck#69]
Hi,

It may be of less importance, but in the icon set I miss a pair of icons for open/closed doors.

Also it could be interesting to add an icon to the light icon set for "AUTO", for example just putting an (cyan?) "A"  in the center of the icon.

I'm preparing a set of icons for the electronic devices and the chocks, I wouldn't mind sharing them with you... but I'm not enough satisfied with the result yet. Anyway, if you're interested I will try to improve them and send them to you.

BR!

**Comment by Fragtality** [comment]
> It may be of less importance, but in the icon set I miss a pair of icons for open/closed doors.

Sorry no Time for that and also I wouldn't know what would be good "general pictogramm" for that - lack of creativity when it comes to Images 😅 

<br/>

> Also it could be interesting to add an icon to the light icon set for "AUTO", for example just putting an (cyan?) "A" in the center of the icon.

Well, how would it sound to you if you could to that by Configuration and would not need an Image for that? 😉 
![image](https://github.com/user-attachments/assets/0239910d-69cf-461f-b1e4-60ea7819b196)

<br/>

> I'm preparing a set of icons for the electronic devices and the chocks, I wouldn't mind sharing them with you... but I'm not enough satisfied with the result yet. Anyway, if you're interested I will try to improve them and send them to you.

That would be a great Contribution, I would certainly look into them and look what to distribute with the Plugin or not!
When they should become "default Icons", I would need them in the three different Quality/Sizes if that would be possible (no postfix => 72x72, @2 postfix => 144x144, @3 postfix 200x100)
Even when they should not become default Icons, we could make a PPP File out of it and make it available in the Integrations Folder 😉
