### ISSUE TITLE
Support for reading offset bit values (like JeeHell)

### ISSUE THREAD

**Issue by rkantos** [Fragtality/PilotsDeck#7]
Hello, thank you for the great StreamDeck plugin! 

I noticed it works quite well with JeeHell FMGS, but not all functionality is possible to achieve in a compact way or in a single button multifunction kind of way since it is not possible to determine a particular function's status by "offset bit value". Also sending commands using similiar way of communication with JeeHell is only partially possible. 

Example of offset table from JeeHell manual:
![image](https://user-images.githubusercontent.com/16664350/114126859-e02d1500-9901-11eb-932c-4f2ee0bdea85.png)
Source: https://jeehell.org/EN%20-%20Advanced%20User%20Guide.pdf

**Comment by Fragtality** [comment]
Hello, you're welcome :)

Hmm, I see your Problem. It is only possible to the read the complete byte and compare its decimal representation (or write the complete byte).
I'll add the support read/write single bits!

**Comment by Fragtality** [comment]
Added in v0.5.1
Please write back if that works.

**Comment by rkantos** [comment]
I will check this out when I figure out why JeeHell really likes to consume CPU in a way which makes Streamdeck software freeze almost completely.

**Comment by Fragtality** [comment]
I would close it now, for me it worked without Problems (tested with the Lights Offset 0D0C).
You're welcome to open a new Issue, should it not work for you!
