### ISSUE TITLE
Developer UI: Aircraft String not displaying actual string matched against

### ISSUE THREAD

**Issue by dotEvan** [Fragtality/PilotsDeck#72]
When looking for a profile to match to, I initially entered in "FNX32", but the correct string would have been "FNX_32". It looks like on the Developer UI the Aircraft String is collapsing the first underscore. (In the screenshot attached, it looks like the underscore is actually under the 3.) However, when looking at the log messages, it correctly displays the Aircraft String and now has found "FNX_32".

![image](https://github.com/user-attachments/assets/3ac92e66-b6f1-4945-a802-49636f8d42b3)

**Comment by Fragtality** [comment]
Wow, good find 👍 

Should be fixed now. Was some dumb WPF Wizardry of the Label Control.
