### ISSUE TITLE
[v0.8.0] Please add an option to remove the icon from the task bar

### ISSUE THREAD

**Issue by ErikNL80** [Fragtality/PilotsDeck#75]
Hi! I am using Pilot's Deck together with Flightpanels.io and StreamDeck XL. I manually updated to v0.8.0 and noticed the icon in the taskbar. It would be nice to have an option to remove the icon from displaying there.

**Comment by Fragtality** [comment]
Screenshot?

**Comment by ErikNL80** [comment]
This is how it looks after installation:
![Schermafbeelding 2024-11-04 205414](https://github.com/user-attachments/assets/163a0c85-eb8d-446c-99ad-08974049fc46)

**Comment by Fragtality** [comment]
That is the System Tray / Notification Area, it is intended to show an Icon there - so no Plans to change anything about that.

You can google how to hide Icons in the Windows Settings.
