### ISSUE TITLE
"$-0.05:0" never reaches the value 0, "$0.05:1" never reaches the value 1

### ISSUE THREAD

**Issue by pre-martin** [Fragtality/PilotsDeck#77]
Environment: X-Plane, ZIBO B738 (but should be independent from the aircraft), PilotsDeck 0.8.0

I have configured a dial like follows:
* Dial Left
  * Type: `X-Plane: DataRef`
  * Command Address: `laminar/B738/electric/panel_brightness[0]` (values from 0 to 1.0)
  * Write Value: `$-0.05:0`
* Dial Right
  * Type: `X-Plane: DataRef`
  * Command Address: `laminar/B738/electric/panel_brightness[0]`
  * Write Value: `$0.05:1`

When the DataRef has the value `1` and I start to turn the dial to the left, I get the following values:
* 0.949999976158142
* 0.899999988079071
* 0.849999976158142
* ...
* 0.0499998450279236

Then the value stays at `0.04` and does not decrease any more. Impossible to get the value `0`. The same happens in the other direction: With the dial, I cannot get values higher than `0.950000166893005`.

I assume that the plugin wants to decrease this last value by 0.05, but it doesn't because 0.049 is already too low. As far as I understood, the expression $-0.05:**0** should decrease the value down to **0**. If I am not wrong, maybe you could implement something, that if the last decrement or increment is too small/high, that you jump to the final value. So from `0.049` to `0` and from `0.095000001....` to `1`.

**Comment by Fragtality** [comment]
Good catch!

Try the Dev Build, should be fixed: https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe

**Comment by pre-martin** [comment]
That fix was really fast. I will test both issues on Friday.

**Comment by Fragtality** [comment]
Fixed with Version 0.8.1
