### ISSUE TITLE
Possible issue with FSUIPC: Control Command Type on FS2024

### ISSUE THREAD

**Issue by KR283** [Fragtality/PilotsDeck#79]
When using a Dynamic button with a Command Type of FSUIPC: Control I get the Error Exclamation mark on 2024 - The same button works OK on FS2020

![image](https://github.com/user-attachments/assets/e0142283-1ac1-4ec4-a80a-2d142f994d56)

**Comment by Fragtality** [comment]
And you have checked that FSUIPC7 is running, yes?
Logs?

**Comment by KR283** [comment]
FSUIPC7 is running (tested with both v7.4.18 & 7.5.0a)

2024-11-22 13:32:43.353 [DBG] [ ActionBaseSimple:OnKeyUp         ] Build Command 
2024-11-22 13:32:43.363 [WRN] [ SimController:CommandTask        ] No active & ready Connector can run the Command 'CONTROL' Command '66288' (Valid-Check: True)

**Comment by Fragtality** [comment]
That is not a Log.

**Comment by KR283** [comment]
[PilotsDeck20241122.log](https://github.com/user-attachments/files/17870897/PilotsDeck20241122.log)

**Comment by Fragtality** [comment]
Interesting - the FSUIPC connector directly closes in the Beginning.
What happens when you restart the Plugin (via its Systray Icon) while you are in a Session?

**Comment by Fragtality** [comment]
Check if the latest DevBuild does any better:
https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe

**Comment by KR283** [comment]
> Interesting - the FSUIPC connector directly closes in the Beginning. What happens when you restart the Plugin (via its Systray Icon) while you are in a Session?

All of the icons on the deck display the three dots waiting image
[PilotsDeck20241122 - Copy.log](https://github.com/user-attachments/files/17871327/PilotsDeck20241122.-.Copy.log)

**Comment by KR283** [comment]
> Check if the latest DevBuild does any better: https://github.com/Fragtality/PilotsDeck/blob/master/Install-PilotsDeck-latest.exe

Dev build appears to handle the FSUIPC: Control correctly

**Comment by Fragtality** [comment]
So the previous Message is irrelevant?

**Comment by KR283** [comment]
Perfect - the new dev build works with FSUIPC: Control, and the 3 dots only show briefly whist re-connecting after restarting the plugin

**Comment by Fragtality** [comment]
Solved in 0.8.3
