### ISSUE TITLE
Dual install of FS2020 + 2024 - WASM module not installed in 2024

### ISSUE THREAD

**Issue by bigjezza** [Fragtality/PilotsDeck#80]
Hey thanks for the work on this, just thought I'd drop a note here for anyone else that has 2020 and 2024 installed, the installer didn't seem to put the WASM module in my 2024 folder, and it wouldn't connect until I put WASM in the 2024 community package folder manually.

**Comment by Fragtality** [comment]
Heyho!

The Installer should do this and in my Testings it worked as intended.
Do you have the Steam or MS Store Version? If MS Store: does the Path
`%localappdata%\Packages\Microsoft.Limitless_8wekyb3d8bbwe\LocalCache\`
exist?

**Comment by Fragtality** [comment]
And what did the Installer say at all? Did it not report any Error/Warning on the Task "MobiFlight Module [2024]" and showed just green?!
