### ISSUE TITLE
MSFS 24 - "OUT_OF_BOUNDS" Exception

### ISSUE THREAD

**Issue by Neverillfly** [Fragtality/PilotsDeck#82]
Hi. I'm receiving an "OUT_OF_BOUNDS" exception while the plugin attempts to connect to MSFS 24. It successfully connects to MSFS 20, so it seems to be related specifically to the new version. Here are the details that may help with troubleshooting:

Plugin version - 0.8.3
[PilotsDeck20241129.log](https://github.com/user-attachments/files/17961261/PilotsDeck20241129.log)
[startup.log](https://github.com/user-attachments/files/17961270/startup.log)
[StreamDeck0.log](https://github.com/user-attachments/files/17961283/StreamDeck0.log)

dotnet --list-runtimes output:
Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Fragtality** [comment]
So did you close because it solved, or should I interpret that? ^^
