### ISSUE TITLE
Buttons Showing "..." After Update

### ISSUE THREAD

**Issue by tron9944** [Fragtality/PilotsDeck#83]
Hi, looks like the installer is recognizing the sim now; however, the buttons on my profiles are no longer displaying. You mentioned SD 6.8... I have updated it to this version. Is it not compatible?

I am running the latest FSUIPC beta for MSFS2024.

Log files attached. Thanks!

[lua.log](https://github.com/user-attachments/files/18030186/lua.log)
[PilotsDeck20241205.log](https://github.com/user-attachments/files/18030187/PilotsDeck20241205.log)
[startup.log](https://github.com/user-attachments/files/18030188/startup.log)

**Comment by Fragtality** [comment]
You are aware of https://github.com/Fragtality/PilotsDeck?tab=readme-ov-file#31---display-behavior ?

**Comment by Fragtality** [comment]
Hmm there is an Issue with the MobiFlight Module - please check if your (2024) Community Folder contains
`mobiflight-event-module`

**Comment by tron9944** [comment]
Yeah I was trying to launch it in the middle of a flight. And yes, my 2024 Community folder has the mobiflight folder.

**Comment by Fragtality** [comment]
Hmm, don't see that here - I mean it was still on the Runway, but I wouldn't know why Flying would make a Difference 🤔 
And is that every Time you start the Sim or was that just one Session?

It could just be the Simulator being buggy - it is in Public Beta at best. Skimming over the latest RSR Update, it seems AdoboSoft has yet again forgotten important WASM Stuff so PMDG can't proceed currently with 2024. And they are Part of the illustrious M$ Revenue Circle that is marketed as "Community". So you can imagine how they care about real People from the real Community doing Stuff for the (real) Community that doesn't earn M$ anything 🤷‍♂️

**Comment by tron9944** [comment]
Looks like a good 'ol power off, power on is all that was required! Back in business now. Thanks for the help on the above issues. Out of curiosity, will we see a DynamicLOD for MSFS24? I have been achieving less than desirable results with the built-in capability (not sure if its logic is altitude-based).

**Comment by Fragtality** [comment]
https://github.com/Fragtality/DynamicLOD/issues/15

**Comment by Fragtality** [comment]
Solved, Solution added to Readme / Troubleshooting Section
