### ISSUE TITLE
Display Value button background images are too large

### ISSUE THREAD

**Issue by richardkennedy** [Fragtality/PilotsDeck#84]
Version: 0.8.5 - Display value buttons with an image background are being displayed incorrectly (too large). By default the Draw Rectangle values are set to 0; 0 and setting this to 72; 72 resolves the issue. The attached image shows two display value buttons, the one on the left has the default value and the one on the right has a set value.

![Capture](https://github.com/user-attachments/assets/d621d848-6563-498d-98c4-6aa17a4b6978)

**Comment by Fragtality** [comment]
Works as intended.
Using non-standard Sizes (any other than 72x72 / 144x144) requires manual Intervention.

**Comment by richardkennedy** [comment]
The images are 144x144
