### ISSUE TITLE
Version number is reported incorrectly within the Stream Deck application

### ISSUE THREAD

**Issue by richardkennedy** [Fragtality/PilotsDeck#85]
Whilst 0.8.5 is installed, the version number is reported as 0.8.0 within the Stream Deck application.

![2024-12-10_09-38-39](https://github.com/user-attachments/assets/ed6dc521-747f-4eb5-a4dc-5555b1ddc7a7)

**Comment by Fragtality** [comment]
Only cosmetic, will be updated with the next Release

**Comment by Fragtality** [comment]
Fixed in 0.8.6
