### ISSUE TITLE
Solution build fails

### ISSUE THREAD

**Issue by ivanleskovar** [Fragtality/PilotsDeck#87]
Hi, 

I've tried to build solution locally but I got errors that two files are missing. I don't see them in repo.

`The command "powershell -ExecutionPolicy Unrestricted -file "CopyLatest.ps1" Debug" exited with code -196608.`

`The command "powershell -ExecutionPolicy Unrestricted -file "BuildPlugin.ps1" Debug" exited with code -196608.`

Did I miss something?

Thx

**Comment by Fragtality** [comment]
Nope, didn't miss something. These are not provided.

**Comment by ivanleskovar** [comment]
Ia there a way to get them?

**Comment by Fragtality** [comment]
Either remove them from the Build-Events or create your own.

They are not required to get Binaries build. It just automates packaging / testing.

**Comment by ivanleskovar** [comment]
Ah, understod.
thx

**Comment by Fragtality** [comment]
The CopyLatest is really just copying the Installer Binary to the Project-Root and renaming it.

BuildPlugin is mostly for creating the whole Package. So for a basic Start you can replace it with a Script that just copies the Plugin / Profile Manager Output directly to the Plugin Directory (Stop / Start the StreamDeck Software before and after). And then add what you need from there 😉 

Maybe one Thing to add: to get the Plugin / Profile Manager as SingleFile Assembly, you need to run dotnet publish. The normal Build Process of VS won't pack the DLLs together (which is fine too).
