### ISSUE TITLE
Multiple versions of FSUIPC cause the installer to fail

### ISSUE THREAD

**Issue by haeriphos** [Fragtality/PilotsDeck#88]
I attempted to install the application and was told that my FSUIPC was out of date and needed to be updated to 7.5. The update succeeded but the installer still said that I did not have the correct version installed. I manually launched FSUIPC and confirmed it was 7.5.0. I reviewed the registry key that the installer uses to determine the FSUIPC version and it was present (v7.5.0). However, I also noticed that I had v6 and an older v7 also installed. I removed both of these and reinstalled v7.5 and the installer then worked correctly.

**Comment by Fragtality** [comment]
It works without Problems with v6 installed.

Log from the Installer? At least a Screenshot? Which Version did you use?

**Comment by haeriphos** [comment]
Sorry, I installed straight from WinRAR so I'm pretty sure any temporary logs were deleted when WinRAR cleaned it up after the installation, and I can't recreate the problem now that I've removed those older versions of FSUIPC. The version of PilotsDeck is 0.8.5 from flightsim.to. Sorry I can't provide more info.

**Comment by Fragtality** [comment]
Can't really troubleshoot something that works on my end without Data :/
Maybe it is very specific Combo 🤔 

- Which MSFS Versions are installed?
- Which FSUIPC Version was installed previously?
- If 7.5.0 Beta-Build: was that installed to only one or both Sims in the FSUIPC Installer? If only one: Which Sim?
- Was the Installation done to only one or both Sims in the FSUIPC Installer? If only one: Which Sim?

**Comment by Fragtality** [comment]
No further Feedback => closed
